import { IScrollItem } from '../../../../components/Elements/Widgets/InfiniteScroll/InfiniteScroll'

export const ICONS: IScrollItem[] = [
  { name: 'react', link: 'colored devicon-react-original' },
  { name: 'angular', link: 'colored devicon-angularjs-plain' },
  { name: 'vue', link: 'colored devicon-vuejs-plain' },
  { name: 'svelte', link: 'colored devicon-svelte-plain' },
  { name: 'node', link: 'colored devicon-nodejs-plain' },
  { name: 'express', link: 'colored devicon-express-original' },
  { name: 'nest', link: 'colored devicon-nestjs-plain' },
  { name: 'gatsby', link: 'colored devicon-gatsby-plain' },
  { name: 'html', link: 'colored devicon-html5-plain' },
  { name: 'css', link: 'colored devicon-css3-plain' },
  { name: 'js', link: 'colored devicon-javascript-plain' },
  { name: 'ts', link: 'colored devicon-typescript-plain' },
  { name: 'python', link: 'colored devicon-python-plain' },
  { name: 'java', link: 'colored devicon-java-plain' },
  { name: 'ruby', link: 'colored devicon-ruby-plain' },
  { name: 'php', link: 'colored devicon-php-plain' },
  { name: 'go', link: 'colored devicon-go-plain' },
  { name: 'csharp', link: 'colored devicon-csharp-plain' },
  { name: 'swift', link: 'colored devicon-swift-plain' },
  { name: 'flutter', link: 'colored devicon-flutter-plain' },
  { name: 'dart', link: 'colored devicon-dart-plain' },
  { name: 'rust', link: 'colored devicon-rust-plain' },
  { name: 'elixir', link: 'colored devicon-elixir-plain' },
  { name: 'haskell', link: 'colored devicon-haskell-plain' },
  { name: 'scala', link: 'colored devicon-scala-plain' },
  { name: 'kotlin', link: 'colored devicon-kotlin-plain' },
  { name: 'docker', link: 'colored devicon-docker-plain' },
  { name: 'kubernetes', link: 'colored devicon-kubernetes-plain' }
]
